COMMIT_TYPE=$1
COMMIT_SCOPE=$2
COMMIT_SUBJECT=$3
COMMIT_EMOJIS=$4
COMMIT_OPTION=$5

_main() {
    echo 'MAIN'
    echo $COMMIT_TYPE
    # if "COMMIT_TYPE"
    # git commit  -m "$COMMIT_TYPE:$COMMIT_EMOJIS $COMMIT_SUBJECT"  $COMMIT_OPTION
}

_main